default_platform(:android)

platform :android do
  desc "Distribute the Dev Android app via Firebase App Distribution"
  lane :distribute_dev do
    properties_file = "../androidApp/version.properties"
    properties = {}
    File.readlines(properties_file).each do |line|
      key, value = line.strip.split('=')
      properties[key] = value if key && value
    end

    properties["devBuildNumber"] = (properties["devBuildNumber"].to_i + 1).to_s

    content = properties.map { |k, v| "#{k}=#{v}" }.join("\n") + "\n"
    File.write(properties_file, content)

    gradle(
      project_dir: ".",
      task: "assemble",
      flavor: "dev",
      build_type: "Debug"
    )

    firebase_app_distribution(
      app: "1:837738262401:android:2928e6c14480ba9e354280",
      testers: ENV.fetch("RAVEN_FASTLANE_TESTERS", "ksdy234@gmail.com"),
      release_notes: "Dev build uploaded via Fastlane",
      apk_path: "androidApp/build/outputs/apk/dev/debug/androidApp-dev-debug.apk"
    )
  end

  desc "Build and upload Prod Release APK to Firebase App Distribution"
  lane :distribute_prod do
    gradle(
      project_dir: ".",
      task: "assemble",
      flavor: "prod",
      build_type: "Release"
    )

    firebase_app_distribution(
      app: "1:837738262401:android:9e67a53d3548a992354280",
      testers: ENV["RAVEN_FASTLANE_TESTERS"],
      release_notes: "Prod build uploaded via Fastlane",
      apk_path: "androidApp/build/outputs/apk/prod/release/androidApp-prod-release-unsigned.apk"
    )
  end
end
