#Gradle
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"

#Kotlin
kotlin.code.style=official

#MPP
kotlin.mpp.stability.nowarn=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2

#Android
android.useAndroidX=true
android.targetSdk=34
android.compileSdk=34
android.minSdk=24

#Versions
kotlin.version=2.0.0
agp.version=8.1.4
compose.version=1.6.11

# Libraries
ktor.version=2.3.7
sqldelight.version=2.0.1
koin.version=3.5.3
serialization.version=1.6.2
kotlin.mpp.applyDefaultHierarchyTemplate=false
